-- MySQL Script generated by MySQL Workbench
-- 06/19/17 15:34:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_vs-oade_admin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_vs-oade_admin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_vs-oade_admin` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_vs-oade_admin` ;

-- -----------------------------------------------------
-- Table `db_vs-oade_admin`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade_admin`.`users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `db_vs-oade_admin`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade_admin`.`questions` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `questionNo` VARCHAR(45) NULL,
  `questionFR` VARCHAR(400) NULL,
  `questionCommentFR` VARCHAR(400) NULL,
  `questionDE` VARCHAR(400) NULL,
  `questionCommentDE` VARCHAR(400) NULL,
  `axes_idAxe` INT NULL,
  PRIMARY KEY (`idQuestion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_vs-oade_admin`.`axes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_vs-oade_admin`.`axes` (
  `idAxe` INT NOT NULL AUTO_INCREMENT,
  `nameFR` VARCHAR(45) NULL,
  `nameDE` VARCHAR(45) NULL,
  PRIMARY KEY (`idAxe`))
ENGINE = InnoDB;


/*SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;*/

INSERT INTO `users`(`username`, `password`) VALUES ('admin', 'pass');

INSERT INTO `axes`(`nameFR`, `nameDE`) VALUES ('société', 'Gesellschaft');
INSERT INTO `axes`(`nameFR`, `nameDE`) VALUES ('économie', 'Wirtschaft');
INSERT INTO `axes`(`nameFR`, `nameDE`) VALUES ('environnement', 'Umwelt');

INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.1', "Quel est l'objectif principal poursuivi par le projet ?", "L'objectif est clair et mesurable, réaliste et valable à long terme.", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.2', "Quels sont les objectifs secondaires poursuivis par le projet ?", "Les objectifs secondaires sont en cohérence par rapport à l'objectif principal.", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.3', "Quels sont les effets souhaités ?", "Les effets du projets sont connus ou observables. Le projet est suffisamment souple pour être adapté si besoin (renforcer des effets positifs, diminuer ou éviter des effets négatifs).", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.4', "Le projet risque-t-il d'avoir des effets secondaires non désirés ?", "Les effets sur l'environnement, les nuisances pour la population, les risques pour l'économie locale, les nuisances lors des travaux (durée, fréquence), la gestion des déchets et transports, etc. ont été reconnus par le porteur du projet.", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.5', "Quels sont les groupes cibles ?", "Des groupes cibles clairs sont visés. Le projet favorise l'intégration de groupes défavorisés (personnes handicapés, jeunes-seniors, communautés étrangères, nouveaux arrivés, petit-budget, etc.).", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.6', "Quels sont les partenaires du projet ?", "La démarche prévoit faire participer les associations, valoriser le bénévolat, faire participer les jeunes/personnes âgées/population/entreprises locales…", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('1.7', "Quel est le budget prévisionnel ?", "Le budget est proportionnel au résultat escompté.", "de", "deComment", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.1', "Que prévoit votre projet pour permettre l'égalité d'accès et l'accessibilité de tous les publics ? (solutions pour personnes qui habitent loin, à mobilité réduite, d'origines et de culture diverses, enfants, personnes âgées, accessibilité financière, etc.)", "favorise la solidarité territoriale", "de", "deComment", 1);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.2', "En quoi le projet contribue-t-il au bien-être social ? (stimule le mouvement, alimentation saine, améliore le sentiment de sécurité, améliore la santé individuelle, répond à un réel besoin exprimé, etc.)", "favorise la santé et le mouvement", "de", "deComment", 1);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.3', "Comment votre projet favorise-t-il la mixité sociale ? (intégration professionnelle, intégration de différentes catégories socio-économiques, échanges entre générations, etc.)", "favorise la cohésion sociale", "de", "deComment", 1);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.4', "Par quels moyens votre projet favorise-t-il l'emploi au niveau local ? (partenariats, réseaux d'acteurs locaux, promotion économique, création et maintien de biens, services et emplois locaux, etc.)", "valorise l'économie locale", "de", "deComment", 2);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.5', "Comment le projet intègre-t-il son coût global dans une optique de long terme ? (ensemble des dépenses générées et autonomie financière, effets du contexte politique ou juridique, réduction des coûts de gestion et d'entretien, durabilité des matériaux, etc.)", "gestion financière responsable", "de", "deComment", 2);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.6', "Pourquoi le projet est-il innovateur ou exemplaire ? (capacité d'innovation, méthode, démarche, outils, partenariats, résultats, etc.)", "est innovateur", "de", "deComment", 2);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.7', "Comment prévoyez-vous limiter la consommation des ressources naturelles ? (consommation d'énergie, consommation d'eau, diminution des déplacements, réduction des déchets à la source, etc.)", "gestion économe des ressources naturelles", "de", "deComment", 3);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.8', "Comment essayez-vous de réduire votre impact négatif sur l'environnement naturel et la biodiversité ? (solutions pour les milieux fragiles, mesures de compensation, limitation des nuisances sonores, lumineuses, pour le sol, l'air ou l'eau, gestion des déplacements et des déchets, etc.)", "faible impact négatif sur la nature et la biodiversité", "de", "deComment", 3);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('2.9', "Qu'est-il prévu pour garantir une bonne intégration de votre projet dans le paysage ?", "intégration dans le paysage", "de", "deComment", 3);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('3.1', "Existe-t-il d'importants conflits d'objectifs entre les trois dimensions du développement durable (c'est-à-dire des améliorations dans l'une des dimensions qui sont succeptibles d'entraîner des détériorations dans une autre) ?", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('3.2', "Faut-il s'attendre à des effets négatifs dans le domaine où la situation s'est déjà aggravée ?", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('3.3', "Le projet conduit-il à des transferts de charges sur les générations futures et/ou peut-il avoir des conséquences irréversibles ou difficilement réparables ?", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('3.4', "Le projet renferme-t-il certains risques, resp. d'importantes incertitudes ?", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('3.5', "Existe-t-il une marge d'optimisation dans la conception du projet qui pourrait, le cas échéant, atténuer des conflits d'objectifs ? Si oui, cette marge est-elle grande ou plutôt restreinte ?", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('3.6', "Le projet peut-il avoir des incidences spatiales qui dépassent le périmètre d'impact visé ( p. ex. des effets globaux) ?", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('5.1', "Conflits d'objectifs entre les trois dimensions du développement durable", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('5.2', "Effets négatifs dans le domaine où la situation s'est déjà aggravée", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('5.3', "Transferts de charges sur les générations futures", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('5.4', "Risques, resp. d'imporatntes incertitudes", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('5.5', "Manque de marge d'optimisation", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('5.6', "Incidences spatiales qui dépassent le périmètre d'impact visé ", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('6.1', "Le projet et ses démarches sont transparents.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('6.2', "Le projet respecte le cadre juridique et réglementaire.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('6.3', "Les acteurs du projets se concertent / les citoyens participent.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('6.4', "Le projet s'appuie sur une processus décisionnel.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('6.5', "Le projet est suivi et régulièrement évalué.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('7.1', "Le projet est localisé dans une zone adaptée.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('7.2', "Le projet utilise les infrastructures existantes ou nécessite de nouvelles infrastructures utiles pour les générations futures.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('7.3', "L'ensemble des déplacements dans le cadre du projet sont évalués, réduits et gérées en favorisant la mobilité douce.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('7.4', "Le projet respecte les sites d'importance historique, culturelle ou naturelle.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('7.5', "Le projet respecte les intérêts des différents usagers du territoire concerné.", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('8.1', "Analyse approfondie / évaluation des effets / indicateurs (Relever les points faibles / conflits potentiels, déterminer des indicateurs significatifs)", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('8.2', "Renforcer la transversalité et les collaborations (Concertation entre les différents acteurs et leurs intérêts)", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('8.3', "Sensibiliser, informer, faire participer (Améliorer la communication ou l'information, accompagner le projet d'une démarche de sensibilisation ou de participation citoyennne)", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('9.1', "Optimiser la viabilité (Améliorer les gains énergétiques et économiques quant aux modes de déplacement, la gestion des déchets, le matériel utilisé, certification ISO 9001, etc.)", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('9.2', "Optimiser la pérennité (Choisir du matériel recyclé, recyclable et facile à entretenir, répondre à un réel besoin, formuler une vision à long terme, responsabiliser les acteurs impliqués, développer les opportunités, inégrer des publics cibles défavorisés, etc.)", "", "de", "", null);
INSERT INTO `questions`(`questionNo`, `questionFR`, `questionCommentFR`, `questionDE`, `questionCommentDE`, `axes_idAxe`) VALUES ('9.3', "Optimiser la qualité (Certification ISO 14001 et 9001, obtenir les labels de qualité et de garantie selon la nature du projet, participer à des réseaux d'échanges, etc.)", "", "de", "", null);
